package es.etg.dam;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

public class InstitutoOracleXeDAOImp implements InstitutoDAO {

    private Connection conn;
    private final String URL = "jdbc:oracle:thin:%s/%s@localhost:1521/XEPDB1";
    private final String DATABASE_USER = "usuario";
    private final String DATABASE_PASS = "usuario";

    public InstitutoOracleXeDAOImp() throws Exception {
        conn = DriverManager.getConnection(
                String.format(URL, DATABASE_USER, DATABASE_PASS)
        );
    }

    @Override
    public void crearTablas() throws SQLException {
        // Crear tabla 'instituto' (alumnos)
        String createInstituto
                = "BEGIN\n"
                + "  EXECUTE IMMEDIATE 'CREATE TABLE instituto ("
                + "nombre VARCHAR2(100) PRIMARY KEY, "
                + "apellido VARCHAR2(100), "
                + "edad NUMBER)';\n"
                + "EXCEPTION WHEN OTHERS THEN\n"
                + "  IF SQLCODE != -955 THEN RAISE; END IF;\n"
                + "END;";

        // Crear tabla 'asignaturas' con FK a instituto(nombre)
        String createAsignaturas
                = "BEGIN\n"
                + "  EXECUTE IMMEDIATE 'CREATE TABLE asignaturas ("
                + "id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "nombre_asignatura VARCHAR2(200), "
                + "nombre_alumno VARCHAR2(100), "
                + "CONSTRAINT fk_asig_alumno FOREIGN KEY (nombre_alumno) REFERENCES instituto(nombre))';\n"
                + "EXCEPTION WHEN OTHERS THEN\n"
                + "  IF SQLCODE != -955 THEN RAISE; END IF;\n"
                + "END;";

        try (Statement st = conn.createStatement()) {
            st.execute(createInstituto);
            st.execute(createAsignaturas);
        }
    }

    @Override
    public List<Alumno> listarAlumnos() throws SQLException {
        final String query = "SELECT nombre, apellido, edad FROM instituto";
        List<Alumno> alumnos = new ArrayList<>();

        PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            String nombre = rs.getString("nombre");
            String apellido = rs.getString("apellido");
            int edad = rs.getInt("edad");

            alumnos.add(new Alumno(nombre, apellido, edad));
        }

        rs.close();
        ps.close();

        return alumnos;
    }

    @Override
    public int insertar(Alumno a) throws SQLException {
        final String sql = "INSERT INTO instituto (nombre, apellido, edad) VALUES (?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, a.getNombre());
        ps.setString(2, a.getApellido());
        ps.setInt(3, a.getEdad());

        int filas = ps.executeUpdate();
        ps.close();

        return filas;
    }

    @Override
    public int actualizar(Alumno a) throws SQLException {
        final String sql = "UPDATE instituto SET apellido=?, edad=? WHERE nombre=?";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, a.getApellido());
        ps.setInt(2, a.getEdad());
        ps.setString(3, a.getNombre());

        int filas = ps.executeUpdate();
        ps.close();

        return filas;
    }

    @Override
    public int borrar(Alumno a) throws SQLException {
        final String sql = "DELETE FROM instituto WHERE nombre=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, a.getNombre());

        int filas = ps.executeUpdate();
        ps.close();

        return filas;
    }

    @Override
    public int insertarAsignatura(Asignatura as) throws SQLException {
        String sql = "INSERT INTO asignaturas(nombre_asignatura, nombre_alumno) VALUES (?,?)";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, as.getNombreAsignatura());
        ps.setString(2, as.getNombreAlumno());

        int filas = ps.executeUpdate();
        ps.close();

        return filas;
    }

    @Override
    public int actualizarAsignatura(Asignatura as) throws SQLException {
        String sql = "UPDATE asignaturas SET nombre_asignatura=? WHERE id=?";
        PreparedStatement ps = conn.prepareStatement(sql);

        ps.setString(1, as.getNombreAsignatura());
        ps.setInt(2, as.getId());

        int filas = ps.executeUpdate();
        ps.close();

        return filas;
    }

    @Override
    public List<Asignatura> listarAsignaturas() throws SQLException {
        List<Asignatura> lista = new ArrayList<>();
        String sql = "SELECT id, nombre_asignatura, nombre_alumno FROM asignaturas";

        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            lista.add(new Asignatura(
                    rs.getInt("id"),
                    rs.getString("nombre_asignatura"),
                    rs.getString("nombre_alumno")
            ));
        }

        rs.close();
        ps.close();

        return lista;
    }

    @Override
    public void listarAlumnosConAsignaturas() throws SQLException {
        String sql = "SELECT i.nombre, a.nombre_asignatura FROM instituto i JOIN asignaturas a ON i.nombre = a.nombre_alumno";

        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            System.out.println(
                    rs.getString("nombre") + " → "
                    + rs.getString("nombre_asignatura")
            );
        }

        rs.close();
        st.close();
    }

    @Override
    public Alumno consultar(String nombre) throws SQLException {
        String sql = "SELECT nombre, apellido, edad FROM instituto WHERE nombre=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nombre);

        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            Alumno a = new Alumno(
                    rs.getString("nombre"),
                    rs.getString("apellido"),
                    rs.getInt("edad")
            );
            rs.close();
            ps.close();
            return a;
        }

        rs.close();
        ps.close();
        return null;
    }
}
